TheEyeAddon.Managers.Debug.Initialize()
TheEyeAddon.Managers.GarbageCollector.Initialize()
TheEyeAddon.Managers.Settings.Initialize()
TheEyeAddon.Managers.SlashCommands.Initialize()
TheEyeAddon.Managers.UI.Initialize()