TheEyeAddon.Libraries.AceConfig = LibStub("AceConfig-3.0")
TheEyeAddon.Libraries.AceGUI = LibStub("AceGUI-3.0")
TheEyeAddon.Libraries.AceLocale = LibStub("AceLocale-3.0")

TheEyeAddon.Managers.Debug.Initialize()
TheEyeAddon.Managers.Icons.Initialize()
TheEyeAddon.Managers.GarbageCollector.Initialize()
TheEyeAddon.Managers.Settings.Initialize()
TheEyeAddon.Managers.SlashCommands.Initialize()
TheEyeAddon.Managers.UI.Initialize()
TheEyeAddon.Managers.FramePools.Initialize()