TheEyeAddon.Managers.Debug:Initialize()
TheEyeAddon.Managers.SlashCommands:Initialize()
TheEyeAddon.Managers.GarbageCollector:Initialize()
TheEyeAddon.Managers.UI:Initialize()
TheEyeAddon.Managers.Settings.Initialize()